default: &default
  adapter: "sqlite3"
  database: "db/development.sqlite"

development:
  <<: *default

test:
  <<: *default
  database: "db/test.sqlite"
  #is the file where you set up all the information to connect to the database
  # The information in the database. yml file is scoped by environment, 
  #allowing you to get a different setting for testing, development or production.